//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiInfox.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApiInfox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;body bgcolor=&quot;#EFEFEF&quot;&gt;
        ///&lt;center&gt;
        ///	&lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; width=&quot;531&quot; height=&quot;320&quot; bgcolor=&quot;#FFF&quot;&gt;
        ///		&lt;tr&gt;
        ///			&lt;td colspan=&quot;3&quot; width=&quot;531&quot; height=&quot;15&quot;&gt;&lt;/td&gt;
        ///		&lt;/tr&gt;
        ///		&lt;tr&gt;
        ///			&lt;td width=&quot;15&quot;&gt;&lt;/td&gt;
        ///			&lt;td width=&quot;500&quot;&gt;
        ///				&lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot;&gt;
        ///					&lt;tr&gt;
        ///						&lt;td&gt;
        ///							Usuário
        ///						&lt;/td&gt;
        ///						&lt;td&gt;[USUARIO]&lt;/td&gt;
        ///					&lt;/tr&gt;
        ///					&lt;tr&gt;
        ///						&lt;td&gt;
        ///							E-mail
        ///						&lt;/td&gt;
        ///						&lt;td&gt;[EMAIL]&lt;/td&gt;
        ///					&lt;/tr&gt;
        ///					&lt;tr&gt;
        ///						&lt;td&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Contato {
            get {
                return ResourceManager.GetString("Contato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;body bgcolor=&quot;#EFEFEF&quot;&gt;
        ///    &lt;center&gt;
        ///        &lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; width=&quot;531&quot; height=&quot;320&quot; bgcolor=&quot;#FFF&quot;&gt;
        ///            &lt;tr&gt;
        ///                &lt;td colspan=&quot;3&quot; width=&quot;531&quot; height=&quot;15&quot;&gt;&lt;/td&gt;
        ///            &lt;/tr&gt;
        ///            &lt;tr&gt;
        ///                &lt;td width=&quot;15&quot;&gt;&lt;/td&gt;
        ///                &lt;td width=&quot;500&quot;&gt;
        ///                    &lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot;&gt;
        ///                        &lt;tr&gt;
        ///                            &lt;td height=&quot;79&quot; colspan=&quot;3&quot;&gt;&lt;/td&gt;
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecuperarSenha {
            get {
                return ResourceManager.GetString("RecuperarSenha", resourceCulture);
            }
        }
    }
}
